import type { Metadata } from "next";
import { ThemeProviderWrapper } from '../components/Theme/themeprovider';
import { ReduxProvider } from"@/redux/redux-provider"
import { Toaster } from "react-hot-toast";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import ReactQueryProvider from "@/react-query/query-provider";
import AppInitializer from "@/app-initializer/initilizer";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
      <ReactQueryProvider>
        <ReduxProvider>
        <ThemeProviderWrapper>
          <AppInitializer>
          {children}
          <Toaster position="top-right" />
          </AppInitializer>
        </ThemeProviderWrapper>
        </ReduxProvider>
      </ReactQueryProvider>
      </body>
    </html>
  );
}
