
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProviderWrapper } from '../components/Theme/themeprovider';
import { ReduxProvider } from"@/redux/redux-provider"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import ReactQueryProvider from "@/react-query/query-provider";
import AppInitializer from "@/app-initializer/initilizer";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <ReactQueryProvider>
        <ReduxProvider>
        <ThemeProviderWrapper>
          <AppInitializer>
          {children}
          </AppInitializer>
        </ThemeProviderWrapper>
        </ReduxProvider>
      </ReactQueryProvider>
        
      </body>
    </html>
  );
}
